checks:
    javascript:
        code_rating: true
        duplicate_code: true

build:
    environment:
        node: '8.7.0'
    dependencies:
        after:
          - 'npm install -g eslint'
    tests:
        override:
            - eslint-run src test
            -
                command: 'npm run test:coverage:clover'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
